# Change these first
owner: jamiew0w
repo: status.nuked.me
  
# Add your sites here
sites:
  - name: nuked.me
    url: https://nuked.me
  - name: api.nuked.me
    url: https://api.nuked.me
    expectedStatusCodes:
      - 404
  - name: comms.nuked.me
    url: https://comms.nuked.me
  - name: push.nuked.me
    url: https://push.nuked.me
  - name: ingest.nuked.me
    url: https://ingest.nuked.me

assignees:
  - jamiew0w

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.nuked.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.nuked.me
  theme: dark

i18n:
  footer: <a href="https://nuked.me" target="_blank">nuked.me</a>

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
